GET http://localhost:3000/

GET http://localhost:3000/api/users

GET http://localhost:3000/api/user/0
GET http://localhost:3000/api/user/1

GET http://localhost:3000/api/user/tobi/jobs/?api-key=foo

GET http://localhost:3000/api/admin/user/0
x-auth:'scsa'

GET http://localhost:3000/companies?api-key=foo

POST http://localhost:3000/companies?api-key=foo
Content-Type: application/json

{
    "company":{
        "name":"new company-x"
    }
}